### ISSUE TITLE
Docs on curry unclear

### ISSUE THREAD

**Issue by Izhaki** [folktale/folktale.github.io#12]
For an FP Layperson like me, would be nice if the docs on [curry](http://docs.folktalejs.org/en/latest/api/core/lambda/curry.html#examples) would explain why in the last example one gets `TypeError: 2 is not a function`:

```
function sub3(a, b, c){ return a - b - c }

curry(3, sub3)(5)(2)(1)      // => 2
curry(3, sub3)(5, 2)(1)      // => 2
curry(3, sub3)(5)(2, 1)      // => 2
curry(3, sub3)(5, 2, 1)      // => 2
curry(3, sub3)(5, 2, 1, 0)   // => TypeError: 2 is not a function
```

**Comment by robotlolita** [comment]
This happens because `curry(arity, fn)` creates a new function that takes exactly `arity` arguments, **one at a time**. Additionally the function allows you to write things like `f(a, b, c)` as sugar for `f(a)(b)(c)`. The last example throws a type error because it's passing 4 arguments, and `sub3` only takes 3 arguments, so the last argument is passed to whatever `sub3(5)(2)(1)` returns, which is the number 2.

This behaviour was changed in the new library because it made things too confusing when using these functions with regular JS libraries. The new behaviour is documented here (details of the implementation are in the "How Folktale's `curry` works" section): http://origamitower.github.io/folktale/api/en/folktale.src.core.lambda.curry.curry.html

**Comment by Izhaki** [comment]
Thanks @robotlolita, my confusions stemmed from the fact that the second argument is `2`, so the `2` in the error message was associated with the evidence in front - the number you see.

There is quite a bit of mental mapping in FP, like one would have to:

- Understand how curry works
- Recall that the result of `(5, 2, 1)` is `2`
- That that `2` is than given to the function returned by `curry`
- That it expects a function (hence the `2 is not a function` error.

So there's a lot you need to know and keep in mind to understand this error.

The new docs you've linked are much clearer on this issue.

I'm  not sure for how long the old docs are going to live for. But if we're looking at more than 6 months. I suggest at least a minor fix to the docs. It is, essentially, help people onboard the library.
