### ISSUE TITLE
Folktale By Example tutorial document seems truncated?

### ISSUE THREAD

**Issue by srdjan** [folktale/folktale.github.io#8]

**Comment by ahri** [comment]
I don't know anything about category theory and would find the guide really helpful, that being said this ticket was closed over a year and a half ago and the guide is still truncated; should I look elsewhere for this type of thing? Does https://github.com/MostlyAdequate/mostly-adequate-guide fit the bill?

**Comment by robotlolita** [comment]
@ahri oh, it was closed because I assumed just a question about the current state of things. Since then I haven't really had much time to work on this though, but hopefully will be able to work on it ~June this year.

But, yeah, @DrBoolean's Mostly Adequate Guide to FP is a very good resource to learn these concepts. It isn't about Folktale in particular, but it covers many of the concepts that are used :)
